# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3928725f113ac6a405281a74c9847c80676ce4f737cad1abf27872ceb3aaacc4da440a57206ffff56ed3db450710d6f17152546a208c3b80c8ac1f7acaa0b519

test:
  secret_key_base: a78c6a1b6355f503b1476ae429f7dae8d67f854545c7391d738936e51b5eab97203ca6d627bc8002207d4543c2532ad32af648334e613476620321272085d393

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
